# Data mining of statistics from OECD on the countries of USA and Spain

**Source: https://data.oecd.org/**

In [300]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import urllib3
import ssl
import re

**In case that the server doesn't support "RFC 5746 secure renegotiation" and the client is using OpenSSL 3, one needs to:**

Source: https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled

In [301]:
class CustomHttpAdapter (requests.adapters.HTTPAdapter):
    # "Transport adapter" that allows us to use custom ssl_context.

    def __init__(self, ssl_context=None, **kwargs):
        self.ssl_context = ssl_context
        super().__init__(**kwargs)

    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = urllib3.poolmanager.PoolManager(
            num_pools=connections, maxsize=maxsize,
            block=block, ssl_context=self.ssl_context)


def get_legacy_session():
    ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    ctx.options |= 0x4  # OP_LEGACY_SERVER_CONNECT
    session = requests.session()
    session.mount('https://', CustomHttpAdapter(ctx))
    return session

In [302]:
# get the URLs
url_usa = "https://data.oecd.org/united-states.htm" 
url_spain = "https://data.oecd.org/spain.htm"

In [303]:
# get the html data
html_data_usa = get_legacy_session().get(url_usa).text
html_data_spain  = get_legacy_session().get(url_spain).text

In [304]:
# the beautiful soup data
soup_usa = BeautifulSoup(html_data_usa, 'html')
soup_spain = BeautifulSoup(html_data_spain, 'html')

In [408]:
def table_reader(soup_object, country = str):
    """This function takkes the soup object and picks the entries desired."""
    
    i = 0
    table = {}
    headline = []

    for table_i in soup_object.find_all('table'):
        i += 1

        for row in table_i.find("thead").find_all('tr'):
            title = row.find("span").text
            table[i] = pd.DataFrame(columns=["Topic", "Data for {0}".format(country), "Details for {0}".format(country)])
            headline.append(title)

        for row in table_i.find("tbody").find_all('tr'):
            col = row.find_all("td")
            col0_main_entry = col[0].find("a")
            topic = col0_main_entry.find("span").text
            
            col2_main_entry = col[2].find_all('span')
            if len(col2_main_entry) == 0:
                data = 0
                details = 0
            else:
                data = col2_main_entry[0].text
                details = col2_main_entry[2].text

            table[i].loc[len(table[i])] = [topic, data, details]
            
    return headline, table

In [409]:
# get the tables
headlines_usa, tables_usa = table_reader(soup_usa,'USA')
headlines_spain, tables_spain = table_reader(soup_spain,'Spain')

In [438]:
headlines_spain[11]

' Society'

In [436]:
tables_spain[12]

,Topic,Data for Spain,Details for Spain
0,Fertility rates,1.36,\nTotal\nChildren/woman\n2020\nSpain\n
1,National population distribution,48.7,\nUrban regions\nPercentage\n2014\nSpain\n
2,Permanent immigrant inflows,349 794.0,\nTotal\nNumber\n2019\nSpain\n
3,Poverty rate,0.15,\nTotal\nRatio\n2019\nSpain\n
4,Social spending,28.1,\nPublic\n% of GDP\n2022\nSpain\n

In [127]:
def table_unificator(table1, table2):
    """This function put the tables together."""

    new_table = table1.drop(table1.columns[[0]], axis=1)
    table2 = table2.join(new_table)

    return table2

In [464]:
def pipeline(headlines_spain, headlines_usa, tables_spain, tables_usa):
    """This is a pipeline to put it all together (all the different tables) in one big dataframe."""
    
    for i in range(len(headlines_spain)):
        
        # for 1 common table
        table_x = tables_spain[i+1] 
        table_y = tables_usa[i+1]
        table_z = table_unificator(table_x, table_y)
        
        # adding a title column
        new_col = [headlines_spain[i]] + (table_z.shape[0]-1)*['Nan'] 
        table_z.insert(loc=0, column="Table", value=new_col)
        # now the coomon table is done
        
        if i == 0:
            df = table_z
        else:
            df = pd.concat([df,table_z])
    
    return df

In [465]:
df = pipeline(headlines_spain, headlines_usa, tables_spain, tables_usa)
df

,Table,Topic,Data for USA,Details for USA,Data for Spain,Details for Spain
0,Agriculture,Agricultural land,265 266.27,\nPermanent pasture\nThousand hectares\n2019\n...,7 495.98,\nPermanent pasture\nThousand hectares\n2021\n...
1,Nan,Agricultural support,10.5,\nProducer support (PSE)\n% of gross farm rece...,0,0
2,Nan,Crop production,3.61,\nWheat\nTonnes/hectare\n2030\nUnited States\n,0,0
3,Nan,Fish landings,4 161 177.0,\nNational landings in domestic ports\nTonnes\...,312 781.2,\nNational landings in domestic ports\nTonnes\...
4,Nan,Nutrient balance,30.5,\nNitrogen\nKilograms/hectare\n2019\nUnited St...,49.3,\nNitrogen\nKilograms/hectare\n2017\nSpain\n
0,Development,Distribution of net ODA,11 808.8,\nLeast developed countries\nMillion US dollar...,157.4,\nLeast developed countries\nMillion US dollar...
1,Nan,Grants by private agencies and NGOs,4 953.0,\nTotal\nMillion US dollars\n2021\nUnited Stat...,1.9,\nTotal\nMillion US dollars\n2021\nSpain\n
2,Nan,Net ODA,0.2,\nODA grant equivalent\n% of gross national in...,0.3,\nODA grant equivalent\n% of gross national in...
3,Nan,Private flows,159 212.2,\nTotal\nMillion US dollars\n2021\nUnited Stat...,3 799.9,\nTotal\nMillion US dollars\n2021\nSpain\n
4,Nan,Total official and private flows,229 521.9,\nTotal\nMillion US dollars\n2021\nUnited Stat...,7 022.0,\nTotal\nMillion US dollars\n2021\nSpain\n
0,Economy,Composite leading indicator (CLI),98.49,\nAmplitude adjusted\nLong-term average = 100\...,98.27,\nAmplitude adjusted\nLong-term average = 100\...
1,Nan,Household disposable income,0.00,"\nGross\nPer capita, percentage change, previo...",-2.76,"\nGross\nPer capita, percentage change, previo..."
2,Nan,Labour compensation per hour worked,3.8,\nTotal\nAnnual growth rate (%)\n2021\nUnited ...,-0.5,\nTotal\nAnnual growth rate (%)\n2021\nSpain\n
3,Nan,Net national income,59 557,\nTotal\nUS dollars/capita\n2021\nUnited States\n,34 005,\nTotal\nUS dollars/capita\n2021\nSpain\n
4,Nan,Trade in goods and services,10.9,\nExports\n% of GDP\n2021\nUnited States\n,41.6,\nExports\n% of GDP\n2022\nSpain\n
0,Education,Education spending,35 347,\nTertiary\nUS dollars/student\n2019\nUnited S...,14 237,\nTertiary\nUS dollars/student\n2019\nSpain\n
1,Nan,Mathematics performance (PISA),482,\nBoys\nMean score\n2018\nUnited States\n,485,\nBoys\nMean score\n2018\nSpain\n
2,Nan,Reading performance (PISA),494,\nBoys\nMean score\n2018\nUnited States\n,485,\nBoys\nMean score\n2015\nSpain\n
3,Nan,Science performance (PISA),503,\nBoys\nMean score\n2018\nUnited States\n,484,\nBoys\nMean score\n2018\nSpain\n
4,Nan,"Youth not in employment, education or training...",9.3,\n15-19 year-old men\n% in same age group\n202...,8.5,\n15-19 year-old men\n% in same age group\n202...
0,Energy,Crude oil production,559 454.7,\nTotal\nThousand toe\n2021\nUnited States\n,5.9,\nTotal\nThousand toe\n2021\nSpain\n
1,Nan,Infrastructure investment,92 033 898 305.08,\nRoad\nEuro\n2021\nUnited States\n,3 959 000 000.00,\nRoad\nEuro\n2021\nSpain\n
2,Nan,Passenger transport,6 558 301.0,\nRoad\nMillion passenger-kilometres\n2017\nUn...,284 467.0,\nRoad\nMillion passenger-kilometres\n2020\nSp...
3,Nan,Primary energy supply,0.10,\nTotal\nToe/1 000 US dollars\n2021\nUnited St...,0.07,\nTotal\nToe/1 000 US dollars\n2021\nSpain\n
4,Nan,Road accidents,13,\nDeaths\nPer 1 000 000 inhabitants\n2021\nUni...,3,\nDeaths\nPer 1 000 000 inhabitants\n2020\nSpa...
0,Environment,Air and GHG emissions,13.6,\nCarbon dioxide (CO2)\nTonnes/capita\n2021\nU...,4.4,\nCarbon dioxide (CO2)\nTonnes/capita\n2021\nS...
1,Nan,Municipal waste,811.5,\nTotal\nKilograms/capita\n2018\nUnited States\n,472.8,\nTotal\nKilograms/capita\n2021\nSpain\n
2,Nan,Water withdrawals,387 242.0,\nTotal\nMillion m3\n2015\nUnited States\n,29 445.9,\nTotal\nMillion m3\n2020\nSpain\n
0,Finance,Broad money (M3),174.86,\nTotal\n2015=100\nFeb-2023\nUnited States\n,0,0
1,Nan,Long-term interest rates,3.7,\nTotal\n% per annum\nMar-2023\nUnited States\n,3.4,\nTotal\n% per annum\nMar-2023\nSpain\n
2,Nan,Net pension replacement rates,50.5,\nMen\n% of pre-retirement earnings\n2020\nUni...,80.3,\nMen\n% of pre-retirement earnings\n2020\nSpa...
3,Nan,Net pension wealth,8.8,\nMen\nMultiple of annual gross earnings\n2020...,16.0,\nMen\nMultiple of annual gross earnings\n2020...
4,Nan,Short-term interest rates,4.9,\nTotal\n% per annum\nMar-2023\nUnited States\n,2.9,\nTotal\n% per annum\nMar-2023\nSpain\n
0,Government,General government spending,44.9,\nTotal\n% of GDP\n2021\nUnited States\n,50.6,\nTotal\n% of GDP\n2021\nSpain\n
1,Nan,Government reserves,91 322.5,\nTotal\nSDR millions\nQ4-2014\nUnited States\n,27 576.4,\nTotal\nSDR millions\nQ4-2014\nSpain\n
2,Nan,Tax on corporate profits,1.6,\nTotal\n% of GDP\n2021\nUnited States\n,2.7,\nTotal\n% of GDP\n2021\nSpain\n
3,Nan,Tax revenue,26.6,\nTotal\n% of GDP\n2021\nUnited States\n,38.4,\nTotal\n% of GDP\n2021\nSpain\n
4,Nan,Tax wedge,28.4,\nTotal\n% of labour cost\n2021\nUnited States\n,39.3,\nTotal\n% of labour cost\n2021\nSpain\n
0,Health,Health spending,12 318,\nTotal\nUS dollars/capita\n2021\nUnited States\n,3 718,\nTotal\nUS dollars/capita\n2020\nSpain\n
1,Nan,Hospital beds,2.8,\nTotal\nPer 1 000 inhabitants\n2019\nUnited S...,3.0,\nTotal\nPer 1 000 inhabitants\n2020\nSpain\n
2,Nan,Length of hospital stay,5.40,\nAcute care\nDays\n2019\nUnited States\n,6.40,\nAcute care\nDays\n2020\nSpain\n
3,Nan,Life expectancy at birth,74.2,\nMen\nYears\n2020\nUnited States\n,80.3,\nMen\nYears\n2021\nSpain\n
4,Nan,Overweight or obese population,73.1,\nMeasured\n% of population aged 15+\n2019\nUn...,0,0
0,Innovation and Technology,Gross domestic spending on R&D,3.5,\nTotal\n% of GDP\n2021\nUnited States\n,1.4,\nTotal\n% of GDP\n2021\nSpain\n
1,Nan,ICT value added,7.1,\nTotal\n% of value added\n2011\nUnited States\n,4.6,\nTotal\n% of value added\n2011\nSpain\n
2,Nan,Internet access,81.8,\nTotal\n% of all households\n2021\nUnited Sta...,96.1,\nTotal\n% of all households\n2022\nSpain\n
3,Nan,Mobile broadband subscriptions,171.6,\nTotal\nPer 100 inhabitants\nQ2-2022\nUnited ...,109.9,\nTotal\nPer 100 inhabitants\nQ2-2022\nSpain\n
4,Nan,Triadic patent families,13 039.8,\nTotal\nNumber\n2020\nUnited States\n,321.9,\nTotal\nNumber\n2020\nSpain\n
0,Jobs,Average wages,74 737.8,\nTotal\nUS dollars\n2021\nUnited States\n,39 202.3,\nTotal\nUS dollars\n2021\nSpain\n
1,Nan,Employment rate,71.4,\nTotal\n% of working age population\nQ4-2022\...,64.3,\nTotal\n% of working age population\nQ4-2022\...
2,Nan,Hours worked,1 791,\nTotal\nHours/worker\n2021\nUnited States\n,1 641,\nTotal\nHours/worker\n2021\nSpain\n
3,Nan,Long-term unemployment rate,23.1,\nTotal\n% of unemployed\n2021\nUnited States\n,41.7,\nTotal\n% of unemployed\n2021\nSpain\n
4,Nan,Self-employment rate,6.6,\nTotal\n% of employment\n2021\nUnited States\n,15.8,\nTotal\n% of employment\n2021\nSpain\n
0,Society,Fertility rates,1.64,\nTotal\nChildren/woman\n2020\nUnited States\n,1.36,\nTotal\nChildren/woman\n2020\nSpain\n
1,Nan,National population distribution,42.1,\nUrban regions\nPercentage\n2014\nUnited Stat...,48.7,\nUrban regions\nPercentage\n2014\nSpain\n
2,Nan,Permanent immigrant inflows,1 030 990.0,\nTotal\nNumber\n2019\nUnited States\n,349 794.0,\nTotal\nNumber\n2019\nSpain\n
3,Nan,Poverty rate,0.15,\nTotal\nRatio\n2021\nUnited States\n,0.15,\nTotal\nRatio\n2019\nSpain\n
4,Nan,Social spending,22.7,\nPublic\n% of GDP\n2021\nUnited States\n,28.1,\nPublic\n% of GDP\n2022\nSpain\n

In [466]:
# export df to a .csv file
df.to_csv("output.csv", index=False)